name: Build and Test
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'pnpm-lock.yaml'
  # Instead of pull_request to use secrets:
  # See https://github.com/orgs/community/discussions/50161
  pull_request_target:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'pnpm-lock.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm build

      - name: Test
        env:
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
        run: pnpm test
